name: Build and Deploy to Server

on:
  push:
    branches:
      - master  # O la rama que quieras usar

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'  # O la versión que estés utilizando

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the project
      run: dotnet publish -c Release -o ./publish --no-restore

    - name: Copy files via SSH
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ubuntu
        key: ${{ secrets.SERVER_SSH_KEY }}
        source: ./publish/*
        target: /var/www/HFPMApi/  # Ruta en tu servidor donde están los archivos

    - name: Restart the service
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ubuntu
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: sudo systemctl restart HFPMApi.service  # Nombre de tu servicio
